[options]
admin_passwd = admin123
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = odoo19
addons_path = D:\odoo19\odoo19\addons,D:\odoo19\custom_addons
http_port = 8070
gevent_port = 8073
logfile = D:\odoo19\odoo19.log
data_dir = D:\odoo19\odoo19_data
