from . import product_brand

from . import connector
from . import woo_instance
from . import woo_connection_health_log
from . import woo_sync_base
from . import woo_sync_engine
from . import woo_dashboard
from . import woo_sync_dashboard
from . import woo_auto_mapping
from . import woo_product_sync
from . import woo_customer_sync
from . import woo_order_sync
from . import woo_category_sync
from . import woo_coupon_sync
from . import woo_report
from . import woo_report_line
from . import product_template
from . import woo_order_line_sync
from . import woo_sync_status   # 🔥 MUST BE HERE
from . import woo_field
from . import woo_field_mapping
from . import woo_inventory
from . import woo_webhook_sync
from . import woo_webhook_log
from . import woo_ai_error_assistant
from . import woo_sync_timeline
from . import woo_ai_insight
from . import woo_ai_content_wizard
from . import woo_import_by_id_wizard
from . import woo_import_date_range_wizard
from . import woo_sync_preview
from . import woo_manual_record_sync
from . import res_config_settings
from . import ir_actions_report
