{
    "name": "Odoo WooCommerce Connector",
    "version": "19.0.1.0.0",
    "summary": "Sync WooCommerce data with Odoo",
    "category": "Sales",
    "author": "Your Company",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "bus",
        "product",
        "sale_management",
        "contacts",
        "stock",
        "stock_delivery",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/product_action.xml",
        "data/cron.xml",
        "views/woo_instance_view.xml",
        "views/woo_import_by_id_wizard_view.xml",
        "views/woo_import_date_range_wizard_view.xml",
        "views/woo_sync_preview_view.xml",
        "views/woo_manual_record_sync_views.xml",
        "views/woo_connection_health_log_view.xml",
        "views/woo_auto_mapping_views.xml",
        "views/woo_field_mapping_views.xml",
        "views/product_template_woo_view.xml",
        "views/product_brand_view.xml",
        "views/woo_category_sync_view.xml",
        "views/woo_coupon_sync_view.xml",
        "views/woo_product_sync_view.xml",
        "views/woo_product_sync_form.xml",
        "views/woo_ai_content_wizard_views.xml",
        "views/woo_customer_sync_view.xml",
        "views/woo_order_sync_view.xml",
        "views/woo_report_view.xml",
        "views/woo_queue_monitor_view.xml",
        "views/woo_webhook_log_view.xml",
        "views/woo_sync_timeline_view.xml",
        "views/woo_sales_report.xml",
        "views/woo_order_report.xml",
        "views/woo_inventory_views.xml",
        "views/woo_res_config_settings_view.xml",
        "data/woo_order_cron.xml",
        "views/woo_sync_dashboard_view.xml",
        "views/woo_dashboard_action.xml",
        "views/woo_actions.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "woo_connector/static/src/xml/chatbot.xml",
            "woo_connector/static/src/js/chatbot.js",
            "woo_connector/static/src/scss/chatbot.scss",
            "woo_connector/static/src/xml/woo_field_help_panel.xml",
            "woo_connector/static/src/js/woo_field_help_panel.js",
            "woo_connector/static/src/css/woo_field_help_panel.css",
            "woo_connector/static/src/xml/woo_dashboard_templates.xml",
            "woo_connector/static/src/js/woo_dashboard.js",
            "woo_connector/static/src/css/woo_dashboard.css",
            "woo_connector/static/src/css/woo_instance_kanban.css",
            "woo_connector/static/src/css/woo_product_list.css",
        ],
    },
    "installable": True,
    "application": True,
}
